#!/bin/bash
#
# Temporarily unpack a CLTools DMG and get the Clang version.
# Copyright (C) 2014 Niklas Rosenstein
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

tempdir="/tmp/$RANDOM.$RANDOM"
username="$(id -u -nr $(id -u))"
sudo ./install.py "$1" "$tempdir" --owner "$username" --no-sdk --quiet
echo "$("$tempdir/Library/Developer/CommandLineTools/usr/bin/clang" --version)"
sudo rm -r "$tempdir"

