#!/bin/bash
# Activate Mac OS X Command Line Tools in the current shell.
# Copyright (c) 2017  Niklas Rosenstein
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

ABSDIR=$(dirname ${BASH_SOURCE[0]})

# In older versions of the CLTools, this path contained even
# the binaries, newer versions contain the libraries and includes
# here.
USR="$ABSDIR/usr"

# Determine the path to the usr/ directory that contains
# the binaries. The path differs between different versions
# of the CLTools.
USR_TOOLS="$ABSDIR/Library/Developer/CommandLineTools/usr"
if [ ! -e "$USR_TOOLS/bin/clang" ]; then
    USR_TOOLS="$USR"
fi

# Export the new binary path.
export CLTOOLS_BIN="$USR_TOOLS/bin"
export PATH="$CLTOOLS_BIN:$PATH"

# The include path for all languages.
INCLUDE_BASE="$USR_TOOLS/include:$USR/include"

# Export the new library and include paths.
export LD_LIBRARY_PATH="$USR_TOOLS/lib:$USR/lib:$LD_LIBRARY_PATH"
export C_INCLUDE_PATH="$INCLUDE_BASE:$USR/include:$C_INCLUDE_PATH"
export CPLUS_INCLUDE_PATH="$INCLUDE_BASE:$(echo $USR/include/c++/*):$CPLUS_INCLUDE_PATH"
export OBJC_INCLUDE_PATH="$INCLUDE_BASE:$OBJC_INCLUDE_PATH"
export OBJCPLUS_INCLUDE_PATH="$INCLUDE_BASE:$USR/include/objc:$OBJCPLUS_INCLUDE_PATH"
