#!/bin/bash
#
# Activate Mac OS X Command Line Tools in the current shell.
# Copyright (C) 2014 Niklas Rosenstein
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

ABSDIR=$(dirname ${BASH_SOURCE[0]})

# In older versions of the CLTools, this path contained even
# the binaries, newer versions contain the libraries and includes
# here.
USR="$ABSDIR/usr"

# Determine the path to the usr/ directory that contains
# the binaries. The path differs between different versions
# of the CLTools.
USR_TOOLS="$ABSDIR/Library/Developer/CommandLineTools/usr"
if [ ! -e "$USR_TOOLS/bin/clang" ]; then
    USR_TOOLS="$USR"
fi

# Export the new binary path.
export CLTOOLS_BIN="$USR_TOOLS/bin"
export PATH="$CLTOOLS_BIN:$PATH"

# The include path for all languages.
INCLUDE_BASE="$USR_TOOLS/include:$USR/include"

# Export the new library and include paths.
export LD_LIBRARY_PATH="$USR_TOOLS/lib:$USR/lib:$LD_LIBRARY_PATH"
export C_INCLUDE_PATH="$INCLUDE_BASE:$USR/include:$C_INCLUDE_PATH"
export CPLUS_INCLUDE_PATH="$INCLUDE_BASE:$(echo $USR/include/c++/*):$CPLUS_INCLUDE_PATH"
export OBJC_INCLUDE_PATH="$INCLUDE_BASE:$OBJC_INCLUDE_PATH"
export OBJCPLUS_INCLUDE_PATH="$INCLUDE_BASE:$USR/include/objc:$OBJCPLUS_INCLUDE_PATH"

